### ISSUE TITLE
How to reduce whitespace between a plot and its legend?

### ISSUE THREAD

**Issue by OSuwaidi** [JetBrains/lets-plot#874] opened 2023-09-09 02:16 UTC
I've been looking around the docs for ways to reduce the whitespace (margin) around the plots, and specifically, between a corr_plot and its legend (attached screenshot for reference).

<img width="436" alt="corr_plot" src="https://github.com/JetBrains/lets-plot/assets/120381151/d0153af5-fee1-49d3-95ca-3cded6dc64a3">

But the only margin-functionality I found was within `theme(axis_title=element_text(margin=margin()))`. However, this doesn't solve the issue since that mainly has to do with the margin between the plot and its axes. In fact, when trying to use it with a corr_plot, it just adds additional x and y labels to the x and y axes, respectively.

Below is the corr_plot code for reference:
```
(corr_plot(df).points(type='full', diag=False)
            .labels(type="full", diag=False)
            .palette_gradient(low='#d73027', mid='#ffffbf', high='#1a9850').build()
            + ggtitle(f"Overall Correlation in {YEAR}")
            + ggsize(800, 570)
            + theme(legend_text=element_text(size=11), axis_text_x=element_text(angle=65))
            + guides(color=guide_colorbar(barwidth=11)))
```

**Comment by alshan** [comment] 2023-09-11 20:46
This looks like an issue with plot layouting :(

Some kind of a workaround could be to try using `legend_position` and `legend_justification` options in `theme()`:
```
p + theme(legend_position=[1, 0.5], legend_justification=[0, 0.5])
```
however it isn't ideal because the legend width is not taken in account in this case and might be get trimmed.
Also, the plot "geom" area horizontally is positioned in the center and the entire picture center of gravity looks shifted to the right :
![image](https://github.com/JetBrains/lets-plot/assets/4430922/b1521375-75d2-49e3-b62d-ca3fe0f5702a)
This might be another issue but have to check with the original ggplot.

---
Tip: for the sake of "debugging" you might want to enable borders around the legend and the plot:
```
p + theme(
    plot_background=element_rect(color="red", size=2),
    panel_background=element_rect(color="blue", size=1), 
    legend_background=element_rect(color="blue", size=1))
```

**Comment by OSuwaidi** [comment] 2023-09-12 11:36
Thanks for the workaround. 

While tinkering the legend's width, position and justification does help in arranging the layout, the problem that arises; as you mentioned, is the plot's center of gravity gets shifted towards the right (horizontally). It seems that by adjusting the legend's properties, it gets an "absolute" position, and the legend is no longer considered within the plot's borders/container, hence the shift.

**Comment by alshan** [comment] 2023-09-12 20:43
Yes, this is exactly what's happening. I still am not sure if this is a bug or an expected behavior.

As for the situation with default position of the legend, I've created an issue: #877
Hopefully, will be fixed soon.

**Closed** 2023-09-13 07:01 UTC
