### ISSUE TITLE
Js import is dropped on cell recalculation

### ISSUE THREAD

**Issue by uppi** [JetBrains/lets-plot#89] opened 2020-02-26 11:14 UTC
1. Plot something (e. g. an example from tutorial)
2. Recalculate the same cell
3. Refresh the page

Expected: 
The plot is still shown

Actual:
No plot is shown, an exception `window.letsPlotCall is not a function` in js console

**Comment by alshan** [comment] 2020-02-26 17:57
Unfortunately, IPython API doesn't seem to provide a way to handle a page refreshment in python.

I recommend to use `load_lets_plot_js()` function somewhere near imports. 

It will reload the library every time the notebook cell is evaluated.

For example: [distributions.ipynb](https://nbviewer.jupyter.org/github/JetBrains/lets-plot/blob/master/docs/examples/jupyter-notebooks/distributions.ipynb)

**Comment by gsteckman** [comment] 2020-03-18 00:12
That Notebook shows an error "Error loading Lets-Plot JS" and no graphs are displayed. I'm getting the same thing on my local installation I created 2 days ago.

> 
> 
> Unfortunately, IPython API doesn't seem to provide a way to handle a page refreshment in python.
> 
> I recommend to use `load_lets_plot_js()` function somewhere near imports.
> 
> It will reload the library every time the notebook cell is evaluated.
> 
> For example: [distributions.ipynb](https://nbviewer.jupyter.org/github/JetBrains/lets-plot/blob/master/docs/examples/jupyter-notebooks/distributions.ipynb)

**Comment by alshan** [comment] 2020-03-18 01:40
Just tried this notebook and it looked fine. Probably there was an interruption of the cdn service. Is it still not working for you?

**Comment by gsteckman** [comment] 2020-03-18 02:28
It seems that there is a problem with rendering on Firefox. I tried with Firefox and a Firefox incognito window and get the same error result. On Chrome it appears as I would expect.  My local Jupyter installation also works as expected on Chrome.

**Comment by alshan** [comment] 2020-03-18 16:02
I can see no problem in Firefox 74.0 (64-bit) on Mac. Can you see any errors in FF browser console?

**Comment by IKupriyanov-HORIS** [comment] 2020-03-18 17:54
@gsteckman could you run Firefox in [Safe Mode](https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode) and check this notebook again (to make sure that the issue is not caused by extensions and/or settings). Also it would be great to see a browser console output.

**Comment by gsteckman** [comment] 2020-03-19 03:53
In Safe Mode, in a private window, everything looks good. Reloading in my regular non safe mode Firefox, I get the following in the console:

![image](https://user-images.githubusercontent.com/27028452/77029967-7a6a9580-695a-11ea-99f5-194d40803e2e.png)

**Comment by IKupriyanov-HORIS** [comment] 2020-03-19 08:04
So this issue is caused by an extension or settings. I would recommend to disable Ad blockers first, then other extensions. Please leave a comment if this will solve your issue (and name of extension) or take a screenshot of **Network** tab from developers tools (you can see it in your screenshot. First you need to open this tab, then reload the notebook to capture the data and select GET request for lets-plot like in example image).
![Screenshot 2020-03-19 at 11 00 36](https://user-images.githubusercontent.com/14200189/77044706-f0114880-69d0-11ea-9a13-4497d59fe951.png)

**Comment by gsteckman** [comment] 2020-03-21 03:17
This was solved by disabling the extension PrivacyBadger (https://www.eff.org/privacybadger). With PrivacyBadger enabled, the GET request for lets-plot-1.2.0rc2.min.js doesn't occur. Thanks for your help.

**Comment by alshan** [comment] 2020-03-30 22:36
@uppi  The issue was fixed in 1.3.0

**Closed by alshan** 2020-03-30 22:36 UTC
